permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author:
  name: Kris
  email: dutwfk@gmail.com
  weibo: http://weibo.com/u/3706884097
  github: http://github.com/dutwfk

# 站点信息
title: KrisのBlog
description: Kris的博客
url: http://dutwfk.github.io
rss_url: /pages/rss.xml

# gavatar头像及Favicon
avatar: http://7u2n3n.com1.z0.glb.clouddn.com/avatar-walk.jpg?imageView2/1/w/100/h/100
favicon: http://b-avatar.qiniudn.com/favicon.ico

# google analytics 设置
ga:
  id: UA-58838391-1
  url: dutwfk.github.io/

# disqus 设置
disqus:
  shortname: dutwfk
